### ISSUE TITLE
Creation of dynamic property Kirby\Cms\Page::$searchHits is deprecated

### ISSUE THREAD

**Issue by shoesforindustry** [bvdputte/kirby-bettersearch#3]
Just though I would let you know that after using your plugin for some time, I'm having some problems with Kirby 3.9.0/PHP 8.2.1 with BetterSearch.

Kirby CMS debugger is throwing an error in: `kirby-bettersearch/src/bettersearch.php `

**Creation of dynamic property Kirby\Cms\Page::$searchHits is deprecated**
_Line 32_
`$page->searchHits  = 0;`

I presume this is not a Kirby issue but rather PHP 8.1 and the deprecation of Dynamic Properties?

Let me know if you need anything else.

**Comment by bogdancondorachi** [comment]
Hi @shoesforindustry, I've made a PR that solves this issue. You can use it until a new release. #4

**Comment by bvdputte** [comment]
Please upgrade to latest version

**Comment by shoesforindustry** [comment]
Thanks bogdancondora and bvdputte, all now working again.
