### ISSUE TITLE
Problems with user-search

### ISSUE THREAD

**Issue by Fantasterei** [bvdputte/kirby-bettersearch#5]
While `$kirby->users()->search($query, 'name')` works as it should, `$kirby->users()->bettersearch($query, 'name')` results in `Call to a member function bettersearch() on null`.

**Comment by bvdputte** [comment]
If you'ld like to use the same logic to search in a users collection, you'ld have to run it like this (with the latest version 2.0.2): `bettersearch(kirby(), kirby()->users(), $query, ['fields' => ['name']])`.
