### ISSUE TITLE
Compatibility to PHP 8.2 and higher

### ISSUE THREAD

**Issue by mynameisfreedom** [bvdputte/kirby-bettersearch#7]
Hi, thank you very much for this great plugin. 

In PHP 8.2 there are warnings of deprecation, for dynamic properties. 
I am sending you a screenshot of an error

![Screenshot 2023-08-12 at 11-15-52 Kirby CMS Debugger](https://github.com/bvdputte/kirby-bettersearch/assets/46815297/ecbdb33b-5981-42ff-9462-79a198156c2d)

**Comment by mynameisfreedom** [comment]
Hint for those who get this warning and still want to use this plugin, you can set the error reporting to skip reporting warnings by adding the code below to the index.php

`error_reporting(E_ERROR | E_PARSE);`

Errors will still be reported, but not warnings like this one.

**Comment by bvdputte** [comment]
Should be fixed 👍
